mitm:
  bin: 'C:\Program Files (x86)\mitmproxy\bin\mitmdump.exe'
  host: 127.0.0.1
  port: 8080

webdriver:
  bin: 'msedgedriver.exe'

rooms:
  - 19829678666
  - https://live.douyin.com/579197336883

http:
  host: 127.0.0.1
  port: 5000

api:
  userinfo: 'https://live.douyin.com/webcast/user/?aid=6383&target_uid='