mitm:
  bin: 'C:\Program Files (x86)\mitmproxy\bin\mitmdump.exe'
  host: 127.0.0.1
  port: 8080

webdriver:
  headless: False
  use: edge
  edge:
    bin: msedgedriver.exe

output:
  use:
    - print
    - xml
    - debug
  xml:
    save_path: "./"
    file_pattern: "{room_id}_{ts}.xml"
  debug:
    save_path:
      error: "./error"
      unknown: "./debug"
      known: False

live:
  rooms:
    - "585723119943"
  users:
    - MS4wLjABAAAAzBItqEvCjPryxn_Y6w6LtRBFDOVNfjvYSJg8VVZFwlw

http:
  host: 127.0.0.1
  port: 5000

api:
  userinfo: 'https://live.douyin.com/webcast/user/?aid=6383&target_uid='